events {}

http {
    upstream module1 {
        server module1:5000;
    }

    upstream module2 {
        server module2:5001;
    }

    upstream module3 {
        server module3:5002;
    }

    server {
        listen 80;

        location /module1 {
            proxy_pass http://module1;
        }

        location /module2 {
            proxy_pass http://module2;
        }

        location /module3 {
            proxy_pass http://module3;
        }
    }
}
